Issue #34: News Feed Page
mostafaboustani/Soen-341 pull request #79
Opened 2020-04-02 23:45 UTC by cottonswab

- Create "feed" component
- Send fetch request to get most recent photo from each user followed (backend api loop (get user.following.photos.photo_n))
- Front end display results

2020-04-02 23:50 UTC, loganmcmullen commented on client/src/pages/homepage.js
>    //             }}
delete this commented out stuff of use /* ------- */

2020-04-02 23:50 UTC, loganmcmullen commented on client/src/pages/homepage.js
> +/*
remove some of the commented stuff

2020-04-02 23:51 UTC, loganmcmullen commented on client/src/components/displayHomepage.js
> +                    {this.state.img.map(item => {
I see you used the template from the profile pictures which is great. Good way to save time and keep consistency throughout

2020-04-02 23:51 UTC, loganmcmullen approved these changes

2020-04-02 23:52 UTC, cottonswab commented on client/src/pages/homepage.js
> +/*
Will do.

2020-04-03 00:01 UTC, gregtuc requested changes
There needs to be an ability to see who posted the photo. I recommend making another state variable and adding the name of the user who's photo it is to the Card. It would also be better if the cards were laid out vertically in a single column, not in Profile-page format. After this is done the request can be pulled in

2020-04-03 00:19 UTC, ginywiny approved these changes

2020-04-03 00:19 UTC, ginywiny commented on client/src/components/displayHomepage.js
> +                                        <Card.Text>This will be the comment section</Card.Text>
These sections will be updated with the comments section that I am still in the process of completing.

2020-04-03 00:36 UTC, gregtuc approved these changes
Perfect. Thanks for making the changes. Looks good

2020-04-03 00:37 UTC, merged